# Generated by Django 4.1.4 on 2022-12-15 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 15, 16, 7, 17, 403885, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
