# Generated by Django 4.1.4 on 2022-12-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_post_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
